#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
BUCK2_BIN_DIR="$SCRIPT_DIR/.buck2_bin"
BUCK2_VERSION=2024-05-01
BUCK2="buck2-$BUCK2_VERSION"

fetch_buck2() {
    local arch
    mkdir -p "$BUCK2_BIN_DIR"
    pushd "$BUCK2_BIN_DIR" || exit

    arch=$(uname -a)
    echo "arch=$arch"
    if [[ $arch =~ "Darwin" ]]; then

        echo buck2-aarch64-apple-darwin.zst
        wget https://github.com/facebook/buck2/releases/download/$BUCK2_VERSION/buck2-aarch64-apple-darwin.zst
    elif [[ $arch =~ "aarch64" || $arch =~ "arm64" ]]; then
        echo buck2-aarch64-unknown-linux-gnu.zst
        wget https://github.com/facebook/buck2/releases/download/$BUCK2_VERSION/buck2-aarch64-unknown-linux-gnu.zst
    else
        echo buck2-x86_64-unknown-linux-gnu.zst
        wget https://github.com/facebook/buck2/releases/download/$BUCK2_VERSION/buck2-x86_64-unknown-linux-gnu.zst
    fi

    unzstd buck2-*.zst
    rm buck2-*.zst
    mv buck2-* $BUCK2
    chmod +x $BUCK2

    popd || exit
}

if [ ! -e "$BUCK2_BIN_DIR/$BUCK2" ]; then
    fetch_buck2
fi

exec "$BUCK2_BIN_DIR/$BUCK2" "$@"
