name: setup-build

runs:
  using: "composite"
  steps:
    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle && cp .github/github-ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
